name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Run swift build
        uses: docker://swiftlang/swift:nightly-focal
        run: |
          swift build
