name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    container: swiftlang/swift:nightly-focal
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Run swift build
        run: |
          swift build
